# Generated by Django 3.2.9 on 2021-12-05 15:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'categorys',
                'verbose_name_plural': 'categoriess',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('number1', models.CharField(default='no:', max_length=250)),
                ('number2', models.CharField(default='no:', max_length=250)),
                ('number3', models.CharField(default='no:', max_length=250)),
                ('categorys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery_app.category')),
            ],
        ),
    ]
